DigitalRetailersInc/Models/LaptopDetails.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DigitalRetailersInc.Models
{
    [Table("LaptopDetails")]
    public class LaptopDetails
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public byte[] Img { get; set; }

    }
}

DigitalRetailersInc/Controllers/LaptopDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DigitalRetailersInc.Data;
using DigitalRetailersInc.Models;
using Microsoft.AspNetCore.Authorization;

namespace DigitalRetailersInc.Controllers
{
    [Authorize]
    public class LaptopDetailsController : Controller
    {
        private readonly DigitalRetailersIncContext _context;

        public LaptopDetailsController(DigitalRetailersIncContext context)
        {
            _context = context;
        }

        // GET: LaptopDetails
        public async Task<IActionResult> Index()
        {
              return _context.LaptopDetails != null ? 
                          View(await _context.LaptopDetails.ToListAsync()) :
                          Problem("Entity set 'DigitalRetailersIncContext.LaptopDetails'  is null.");
        }

        // GET: LaptopDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LaptopDetails == null)
            {
                return NotFound();
            }

            var laptopDetails = await _context.LaptopDetails
                .FirstOrDefaultAsync(m => m.Id == id);
            if (laptopDetails == null)
            {
                return NotFound();
            }

            return View(laptopDetails);
        }

        // GET: LaptopDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LaptopDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Price,Img")] LaptopDetails laptopDetails)
        {
           
            if (!ModelState.IsValid)
            {
                var files = Request.Form.Files;

                if (files.Count > 0)
                {

                    using (var filestream = files[0].OpenReadStream())
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            filestream.CopyTo(memoryStream);
                            laptopDetails.Img = memoryStream.ToArray();
                        }
                    }
                }
                try
                {
                    _context.Add(laptopDetails);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error occurred while saving data: " + ex.Message);
                    // Log the exception for debugging purposes
                }

                return RedirectToAction(nameof(Index));
                
            }
         
           
            return View(laptopDetails);
        }


        // GET: LaptopDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LaptopDetails == null)
            {
                return NotFound();
            }

            var laptopDetails = await _context.LaptopDetails.FindAsync(id);
            if (laptopDetails == null)
            {
                return NotFound();
            }
            return View(laptopDetails);
        }

        // POST: LaptopDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Price,Img")] LaptopDetails laptopDetails)
        {
            if (id != laptopDetails.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)

            {
                var files = Request.Form.Files;

                if (files.Count > 0)
                {

                    using (var filestream = files[0].OpenReadStream())
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            filestream.CopyTo(memoryStream);
                            laptopDetails.Img = memoryStream.ToArray();
                        }
                    }
                }
                try
                {
                    _context.Update(laptopDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LaptopDetailsExists(laptopDetails.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(laptopDetails);
        }

        // GET: LaptopDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LaptopDetails == null)
            {
                return NotFound();
            }

            var laptopDetails = await _context.LaptopDetails
                .FirstOrDefaultAsync(m => m.Id == id);
            if (laptopDetails == null)
            {
                return NotFound();
            }

            return View(laptopDetails);
        }

        // POST: LaptopDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LaptopDetails == null)
            {
                return Problem("Entity set 'DigitalRetailersIncContext.LaptopDetails'  is null.");
            }
            var laptopDetails = await _context.LaptopDetails.FindAsync(id);
            if (laptopDetails != null)
            {
                _context.LaptopDetails.Remove(laptopDetails);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LaptopDetailsExists(int id)
        {
          return (_context.LaptopDetails?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DigitalRetailersInc/Controllers/MyordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DigitalRetailersInc.Data;
using DigitalRetailersInc.Models;

namespace DigitalRetailersInc.Controllers
{
    public class MyordersController : Controller
    {
        private readonly DigitalRetailersIncContext _context;

        public MyordersController(DigitalRetailersIncContext context)
        {
            _context = context;
        }

        // GET: Myorders
        public async Task<IActionResult> Index()
        {
              return _context.Myorders != null ? 
                          View(await _context.Myorders.ToListAsync()) :
                          Problem("Entity set 'DigitalRetailersIncContext.Myorders'  is null.");
        }

        // GET: Myorders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Myorders == null)
            {
                return NotFound();
            }

            var myorders = await _context.Myorders
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (myorders == null)
            {
                return NotFound();
            }

            return View(myorders);
        }

        // GET: Myorders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Myorders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,ItemId,CustomerName,Address,PhoneNum,paymentStatus,DeleveryStatus,DateOrdered,ExpDeleveyDate")] Myorders myorders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(myorders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(myorders);
        }

        // GET: Myorders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Myorders == null)
            {
                return NotFound();
            }

            var myorders = await _context.Myorders.FindAsync(id);
            if (myorders == null)
            {
                return NotFound();
            }
            return View(myorders);
        }

        // POST: Myorders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,ItemId,CustomerName,Address,PhoneNum,paymentStatus,DeleveryStatus,DateOrdered,ExpDeleveyDate")] Myorders myorders)
        {
            if (id != myorders.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(myorders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MyordersExists(myorders.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(myorders);
        }

        // GET: Myorders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Myorders == null)
            {
                return NotFound();
            }

            var myorders = await _context.Myorders
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (myorders == null)
            {
                return NotFound();
            }

            return View(myorders);
        }

        // POST: Myorders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Myorders == null)
            {
                return Problem("Entity set 'DigitalRetailersIncContext.Myorders'  is null.");
            }
            var myorders = await _context.Myorders.FindAsync(id);
            if (myorders != null)
            {
                _context.Myorders.Remove(myorders);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MyordersExists(int id)
        {
          return (_context.Myorders?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }
    }
}

DigitalRetailersInc/Views/LaptopDetails/Create.cshtml
@model DigitalRetailersInc.Models.LaptopDetails

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LaptopDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input type="file" asp-for="Img" class="form-control" name ="Img" />
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DigitalRetailersInc/Views/LaptopDetails/Delete.cshtml
@model DigitalRetailersInc.Models.LaptopDetails

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LaptopDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Img)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DigitalRetailersInc/Views/LaptopDetails/Details.cshtml
@model DigitalRetailersInc.Models.LaptopDetails

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LaptopDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    @*     <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Img )
        </dd> *@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DigitalRetailersInc/Views/LaptopDetails/Edit.cshtml
@model DigitalRetailersInc.Models.LaptopDetails

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LaptopDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input type="file" asp-for="Img" class="form-control" name="Img" />
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DigitalRetailersInc/Views/LaptopDetails/Index.cshtml
@model IEnumerable<DigitalRetailersInc.Models.LaptopDetails>

@{
    ViewData["Title"] = "Index";
}

<h1>Laptop</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Img)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @* @Html.DisplayFor(modelItem => item.Img) *@
                    <img src="data:image;base64,@Convert.ToBase64String(item.Img)" alt="Image" width="120" height="120"/>
            </td>
            <td>
                    <form action="@Url.Action("Create", "Myorders")" method="get">
                        @Html.Hidden("ItemId", item.Id)
                        <input type="submit" value="Order Now" class="btn btn-success"/>
                    </form>
                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
}
    </tbody>
</table>